remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Pineapples]
description: [This site is dedicated to providing a comprehensive exploration of pineapples, offering insights into their origin, appearance, culinary uses, nutritional value, and more, along with useful links for further pineapple-related exploration.]
